### ISSUE TITLE
Problemas com o webservice de prestação de desacordo.

### ISSUE THREAD

**Issue by GabrielSanches372** [Samuel-Oliveira/Java_CTe#16]
Olá, estou fazendo um ajuste da versão do java-cte trocando de 3.00.3 para a 3.00.7 e esta aparecendo este erro.

WARNING-Exception: Exceção não tratada!

Message: WebService de PRESTACAO_DESACORDO não encontrado para Rio Grande do Sul
INFO: br.com.swconsultoria.cte.exception.CteException: WebService de PRESTACAO_DESACORDO não encontrado para Rio Grande do Sul
Cause: null
...
br.com.swconsultoria.cte.exception.CteException: WebService de PRESTACAO_DESACORDO não encontrado para Rio Grande do Sul
	at br.com.swconsultoria.cte.util.WebServiceCteUtil.lambda$getUrl$0(WebServiceCteUtil.java:56)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at br.com.swconsultoria.cte.util.WebServiceCteUtil.getUrl(WebServiceCteUtil.java:55)
	at br.com.swconsultoria.cte.Eventos.envio(Eventos.java:59)
	at br.com.swconsultoria.cte.Eventos.enviarEvento(Eventos.java:40)
	at br.com.swconsultoria.cte.PrestacaoDesacordo.eventoPrestacaoDesacordo(PrestacaoDesacordo.java:26)
	at br.com.swconsultoria.cte.Cte.prestacaoDesacordoCte(Cte.java:217)

o que poderia estar ocorrendo?

obrigrado.

**Comment by Samuel-Oliveira** [comment]
Beleza? Aqui está funcionando 100%
Verifique se você não informou um arquivo ini nas configuracoes do Cte,

**Comment by GabrielSanches372** [comment]
Beleza? Assim eu fiquei testando e ainda não esta funcionando para nós aqui.
